
def main():
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    """
    L = [1, 2]
    i1 = 1
    i2 = 2
    for i in range(4_000_000):
        i3 = i1 + i2
        i1 = i2
        i2 = i3
        i3str = str(i3)
        if i3str[-1] is [2, 4, 6, 8]:
            L.append(i3)   
    return sum(L)

if __name__ == "__main__":
    print(main())